#include "web_page.h"

const char* get_html_page(void) {
    return "<!DOCTYPE html>"
           "<html lang='en'>"
           "<head>"
           "    <meta charset='UTF-8'>"
           "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
           "    <title>Indoor Positioning System</title>"
           "    <style>"
           "        body {"
           "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
           "            background-color: #f4f7fa;"
           "            color: #333;"
           "            margin: 0;"
           "            padding: 20px;"
           "            display: flex;"
           "            flex-direction: column;"
           "            align-items: center;"
           "        }"
           "        h1 {"
           "            color: #007bff;"
           "            margin-bottom: 20px;"
           "        }"
           "        #map {"
           "            border: 2px solid #ddd;"
           "            border-radius: 8px;"
           "            box-shadow: 0 4px 8px rgba(0,0,0,0.1);"
           "            background-color: #fff;"
           "        }"
           "        #info {"
           "            margin-top: 20px;"
           "            padding: 15px;"
           "            background-color: #fff;"
           "            border-radius: 8px;"
           "            box-shadow: 0 4px 8px rgba(0,0,0,0.1);"
           "            width: 300px;"
           "            text-align: center;"
           "        }"
           "        #status {"
           "            font-weight: bold;"
           "        }"
           "    </style>"
           "</head>"
           "<body>"
           "    <h1>Зональное Indoor-Позиционирование</h1>"
           "    <canvas id='map' width='500' height='500'></canvas>"
           "    <div id='info'>"
           "        <p>Статус: <span id='status'>unknown</span></p>"
           "        <p>Время: <span id='timestamp'>00:00:00</span></p>"
           "    </div>"
           "    <script>"
           "        function draw() {"
           "            fetch('/position').then(r => r.json()).then(d => {"
           "                let ctx = document.getElementById('map').getContext('2d');"
           "                ctx.clearRect(0, 0, 500, 500);"
           "                // Фон карты (зоны)"
           "                ctx.fillStyle = '#e9ecef';"
           "                ctx.fillRect(0, 0, 500, 500);"
           "                // Сетка для зон (каждые 100px = 1m)"
           "                ctx.strokeStyle = '#ccc';"
           "                for (let i = 0; i <= 500; i += 100) {"
           "                    ctx.beginPath(); ctx.moveTo(i, 0); ctx.lineTo(i, 500); ctx.stroke();"
           "                    ctx.beginPath(); ctx.moveTo(0, i); ctx.lineTo(500, i); ctx.stroke();"
           "                }"
           "                // Beacon1 (0,0)"
           "                ctx.fillStyle = '#007bff';"
           "                ctx.fillRect(0, 0, 10, 10);"
           "                ctx.fillStyle = '#000';"
           "                ctx.font = '12px Arial';"
           "                ctx.fillText('Beacon 1', 15, 15);"
           "                // Beacon2 (5m = 500px, но canvas 500, так что на 500,0? Жди, расстояние 5m, scale 100px/m)"
           "                ctx.fillStyle = '#007bff';"
           "                ctx.fillRect(500 - 10, 0, 10, 10);  // Beacon2 на (5m, 0)"
           "                ctx.fillText('Beacon 2', 500 - 80, 15);"
           "                // Позиция (scale 100px/m)"
           "                ctx.fillStyle = d.status === 'ok' ? '#28a745' : '#dc3545';"
           "                ctx.fillRect(d.x * 100, d.y * 100, 10, 10);"
           "                // Обновляем info"
           "                document.getElementById('status').textContent = d.status;"
           "                document.getElementById('status').style.color = d.status === 'ok' ? '#28a745' : '#dc3545';"
           "                document.getElementById('timestamp').textContent = d.timestamp;"
           "            }).catch(e => console.error(e));"
           "            setTimeout(draw, 2000);"
           "        }"
           "        draw();"
           "    </script>"
           "</body>"
           "</html>";
}